### ISSUE TITLE
infografia-Ciclo de vida de desarrollo de un sistema

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-1-infografia-Blanca-estela-valerio-rivero#2]
![1](https://github.com/user-attachments/assets/f7e29aa8-991d-4a56-893a-104868d0840a)
![2](https://github.com/user-attachments/assets/70d91d0c-00ba-4902-bfd5-3fc7e1bb8de9)

**Comment by Roldanuriel** [comment]
20/20 Destaca la importancia de la información

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
